version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: super_tajne_haslo
      MYSQL_DATABASE: moja_baza
      MYSQL_USER: uzytkownik
      MYSQL_PASSWORD: tajne_haslo
    ports:
      - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql

volumes:
  mysql_data: